name: Build and deploy Next.js to Azure Web App - frontend-doco

on:
  push:
    branches:
      - main
    paths:
      - "src/app/**"
      - ".github/workflows/main_frontend-doco.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend-doco'
          slot-name: 'Production'
          package: ./src/app
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_603B0301DCBC48CB9000282FE72DCD53 }}
